In [ ]:
# Bismillah

In [1]:
import numpy as np
import pandas as pd

# The Series
    * A one-dimensional array
    * Holds a single data type
    * Allows access to elements through the associated index labels - helps in allignment of multiple series.

In [17]:
np.random.randn(100) # numpy array

array([-0.2142738 , -0.72936542, -0.46762074,  1.60018618,  2.9857811 ,
       -0.66874605, -0.34715573,  2.35727166,  1.36612005, -0.23546234,
        0.59497932,  0.72363345, -0.19773749, -0.34616701, -0.61068664,
       -1.01310776, -1.36318525, -1.51578592, -0.30439966,  0.50364611,
        0.35426746, -0.32429232, -0.32232952,  1.05490757, -0.34131142,
        0.10895273,  0.34881055, -1.37192724,  1.03577095,  0.40880844,
       -0.518049  ,  0.98876839, -0.54289004, -1.26636879, -1.6740122 ,
       -0.47719835, -0.58173242, -0.48533975, -0.33650959,  1.89517647,
       -0.19499892, -2.27269939,  1.09104068,  0.95781754,  0.07993334,
       -0.61847467, -1.40406145,  1.04544771, -1.91208684, -1.8990113 ,
       -1.10224468, -0.41053193, -1.16012454,  2.1093086 , -0.77628369,
       -0.90879237, -0.02170131, -0.73283532,  1.54540938, -0.88404325,
        0.26898248,  1.06248782,  0.00671318, -0.19705513,  0.97320707,
       -0.94886538,  0.25829629,  0.50207107,  0.46002717,  0.16

In [18]:
s = pd.Series(np.random.randn(100)) # pandas series

In [4]:
s

0     0.935821
1     1.844381
2    -1.146162
3    -1.019161
4    -0.065930
        ...   
95   -0.632068
96    0.161490
97    0.012660
98    1.000310
99    1.874498
Length: 100, dtype: float64

In [19]:
# print (np.random.randn(2,4))
print (np.random.randn(5))

[-0.6631439  -0.19503526  1.4316872  -1.2958872  -0.13690251]


In [20]:
s[2] # grab a value located at index 2.

0.01499485325996352

In [21]:
# s[2, 4] # error since no single index, 2 4, exists.

In [22]:
s[[2, 4]] # the inner [] indicates multiple indices given.

2    0.014995
4    0.878744
dtype: float64

In [ ]:
s[5:10] # slicing doesn't need [] since there is no confusion.

In [23]:
s.head()

0   -0.560468
1   -2.633692
2    0.014995
3    0.483068
4    0.878744
dtype: float64

In [24]:
s.tail()

95    0.255396
96   -0.882441
97    1.424949
98    0.584258
99   -1.433918
dtype: float64

In [25]:
s.shape # 100 rows. Attribute and not method.

(100,)

In [26]:
s.index # Attribute and not method.

RangeIndex(start=0, stop=100, step=1)

In [27]:
s.values

array([-0.56046767, -2.63369231,  0.01499485,  0.48306805,  0.87874351,
        1.52418027,  0.59021396,  0.46555268,  1.63253972, -1.10181885,
        0.12764068,  0.93711187,  1.38747658, -1.00883074, -0.72396139,
        0.19803966, -1.10472064,  1.61574664, -0.49863254, -0.49831719,
        0.40409435,  1.11726209, -0.60797471, -0.49835572,  0.61460813,
        0.08149923,  0.35015917,  0.3680609 ,  1.60070932, -0.41175116,
        0.59619842,  0.36501897, -1.69517099,  0.53231569, -0.59462624,
        0.61546082,  0.86387364,  0.73376305,  1.84907862,  0.69863818,
       -1.37201822, -1.92535353, -1.4830904 , -0.36671067, -0.65581083,
       -0.68965717,  0.82896225, -0.56904075,  1.25175662, -1.21401475,
        0.26709485,  0.03942731, -1.01315677,  1.7310397 , -0.13823908,
        0.9302917 ,  1.81308248,  0.50065562,  0.6179493 ,  0.70044821,
        0.84984838, -0.04725793, -1.22203643,  1.89631151, -0.23461342,
       -1.63227555,  0.32132571, -0.18484887, -1.73030353,  0.95

In [28]:
s = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd']) 
# [] to indicate multiple values as usual. Indices assigned at the time of constructing a series.
# Series created through a list.

In [29]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [32]:
s = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})
# Series created through a dictionary. The keys are the indices in the series.

In [34]:
s

a    1
b    2
c    3
d    4
dtype: int64

In [35]:
s = pd.Series([1, 2, 3, 4, np.nan])
# np.nan so that the pandas know that this value is missing.

In [36]:
s

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [ ]:
len(s)
# includes a missing avalue as well.

In [39]:
s.count()
# excludes missing value.

4

In [ ]:
s = pd.Series([10, 3 , 4, 5, 7, 7, 9, 10, np.nan])

In [ ]:
s

In [40]:
s.unique()
# returns only unique values. That is, avoid repeatition of the same value.
# returns the missing value as well.

array([ 1.,  2.,  3.,  4., nan])

In [50]:
s.value_counts()
# returns frrequency distribution in descending order. For ascending order, ascending = True.
# excludes a missing value.

1.0    1
2.0    1
3.0    1
4.0    1
dtype: int64

In [51]:
s.value_counts(ascending = True) # go from smaller values to larger values.

1.0    1
2.0    1
3.0    1
4.0    1
dtype: int64

In [52]:
s.value_counts(normalize = True) # to grab percentages. ascending = False is the default argument.


1.0    0.25
2.0    0.25
3.0    0.25
4.0    0.25
dtype: float64

In [53]:
s1 = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index = ['d', 'c', 'b', 'a'])

In [54]:
s1 + s2
# The allignment is done automatically on the basis of index labels.
# This feature does not exist in numpy array. See below.

a    2
b    4
c    6
d    8
dtype: int64

In [55]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])

In [56]:
a1

array([1, 2, 3, 4])

In [57]:
a2

array([4, 3, 2, 1])

In [58]:
a1 + a2
# each corresponding element from both the arrays must be added. No flexibility of adding any two desriable elements of
# array located at different indices.

array([5, 5, 5, 5])