In [ ]:
# Bismillah

In [1]:
import pandas as pd
import numpy as np

In [2]:
print (np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [3]:
array = np.arange(12).reshape(3, 4)
array
# We get 2-D array.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
array[0]
# it will extract the first row from the 2-D array.

array([0, 1, 2, 3])

In [6]:
print (array[0])
print (array)

[0 1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
array - array[0]
# The subtraction is performed once for each row. This is knows as broadcasting by rows. 
# Operations between a dataframe and series are similar.

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

## Series and DataFrame:

#### By default, arithmetic between dataframe and series matches the index of the series on the dataframe's columns, broadcasting down the rows. In other words, the index of the series will be matched against columns' headings and then the required arithmetic operation will be performed. This will be done for all the rows one by one. This allignment based on columns followed by the arithmetic operation for each row is called Broadcasting Over the Rows (Matching on the columns).

#### The opposite occurs when the allignment is based on rows (index of the series is matched against the rows' indexes/labels in the dataframe) followed by the arithmetic operation for each column is called Broadcasting Over the Columns (Matching on the rows).

In [7]:
frame = pd.DataFrame(np.arange(12).reshape(4, 3), columns = list('bde'), index = ['Pes', 'Isb', 'Lhr', 'Kch'])
frame

b   d   e
Pes  0   1   2
Isb  3   4   5
Lhr  6   7   8
Kch  9  10  11

In [10]:
series = frame.iloc[[0]]
series
# the series contains zeroth row from the dataframe with indexes b, d, and e.

b  d  e
Pes  0  1  2

In [13]:
frame

b   d   e
Pes  0   1   2
Isb  3   4   5
Lhr  6   7   8
Kch  9  10  11

In [14]:
series

b  d  e
Pes  0  1  2

In [15]:
frame - series
# By default, the indexes in the series will be matched against columns' headings in the dataframe and then subtraction will be
# performed. This process will be performed for each row (broadcasting over rows).

b    d    e
Isb  NaN  NaN  NaN
Kch  NaN  NaN  NaN
Lhr  NaN  NaN  NaN
Pes  0.0  0.0  0.0

#### Series2: contains row 1 in the dataframe.

In [16]:
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [19]:
print (frame)
print (series2)

     b   d   e
Pes  0   1   2
Isb  3   4   5
Lhr  6   7   8
Kch  9  10  11
b    0
e    1
f    2
dtype: int64


In [20]:
frame + series2
# same broadcasting over the rows (matching series indexes with the columns' headings in the dataframe).

b   d     e   f
Pes  0.0 NaN   3.0 NaN
Isb  3.0 NaN   6.0 NaN
Lhr  6.0 NaN   9.0 NaN
Kch  9.0 NaN  12.0 NaN

#### Series3: contains column d of the dataframe.

In [21]:
frame

b   d   e
Pes  0   1   2
Isb  3   4   5
Lhr  6   7   8
Kch  9  10  11

In [22]:
series3 = frame['d']
series3

Pes     1
Isb     4
Lhr     7
Kch    10
Name: d, dtype: int64

In [23]:
frame

b   d   e
Pes  0   1   2
Isb  3   4   5
Lhr  6   7   8
Kch  9  10  11

In [25]:
frame - series3
# same broadcasting over the rows (matching series indexes with the columns' headings in the dataframe) and inserting
# missing value for each non-alignment occured. The total number of alignment tried should be 4 (row indexes in 
# the series) multiplied by 4 (number of rows in the dataframe) plus 3 (number of columns in the dataframe) multiplied
# by 4 (number of rows in the dataframe) which results into total number of 28. So, the total number of NaN inserted
# in the new dataframe after subtraction is 28.

Isb  Kch  Lhr  Pes   b   d   e
Pes  NaN  NaN  NaN  NaN NaN NaN NaN
Isb  NaN  NaN  NaN  NaN NaN NaN NaN
Lhr  NaN  NaN  NaN  NaN NaN NaN NaN
Kch  NaN  NaN  NaN  NaN NaN NaN NaN

In [26]:
frame

b   d   e
Pes  0   1   2
Isb  3   4   5
Lhr  6   7   8
Kch  9  10  11

In [27]:
series3

Pes     1
Isb     4
Lhr     7
Kch    10
Name: d, dtype: int64

In [28]:
frame.sub(series3, axis = 'index')
# axis is the axis to match on. In this case, we want to match on the dataframe's row index and broadcast across the columns,
# that is, the alignment is done based on the dataframe's row index and then subtraction is performed and this is done for each
# column now, so broadcasting across the columns.

b  d  e
Pes -1  0  1
Isb -1  0  1
Lhr -1  0  1
Kch -1  0  1

In [30]:
import pandas as pd
import numpy as np

np = np.arange(10)
df = pd.DataFrame(['test':np])

SyntaxError: invalid syntax (3277559665.py, line 5)

In [25]:
# import numpy as np
# import pandas as pd

# np = np.arange(10)

# pd = pd.DataFrame({'a': np, 'alpha':np})
# print (pd)